version: '3'
services:
    bodypix:
        image: bodypix
        restart: always
        build:
            context: ./bodypix
        networks:
            - fakecam
        read_only: true
        ports:
            - 9000:9000

    fakecam:
        image: fakecam
        restart: always
        build:
            context: ./fakecam
        networks:
            - fakecam
        read_only: true
        volumes:
            - ${IMAGE_BACKGROUND}:/src/background.jpg:ro
            - ${IMAGE_FOREGROUND}:/src/foreground.jpg:ro
            - ${IMAGE_FOREGROUND_MASK}:/src/foreground-mask.png:ro
        devices:
            # webcam
            - ${VIDEO_INPUT}:/dev/video0
            # virtual webcam
            - ${VIDEO_OUTPUT}:/dev/video2
        depends_on:
            - bodypix
        command: ["--bodypix-url", "http://bodypix:9000/"]

networks:
    fakecam: